### PR TITLE
Feat/spatial softmax temp

### PR DESCRIPTION
**Pull request by edgarriba**
this PR add a temperature factor in spatial softargmax2d as requested in https://github.com/arraiyopensource/kornia/issues/138

### CODE REVIEW

**Comment by edgarriba** [comment]
@vimalthilak could you review ?

**Comment by vimalthilak** [comment]
@edgarriba I'd be more than happy to review. Could you please give me 24 hours or so for me to complete this task? Thanks

**Comment by edgarriba** [comment]
@vimalthilak sure

**Comment by vimalthilak** [comment]
Does it make sense to add a test where the user is allowed to set grad=False for temperature? If not, PR LGTM

**Comment by edgarriba** [comment]
@vimalthilak I would keep the signature simple. Since the temp comes from user side, should be the user who takes care about this variable. I guess the issue would be only for the module version if the passed temperature is included in the optimizer.

**Comment by edgarriba** [comment]
@vimalthilak thanks for your time. Feel free to contribute or request features anytime :D

**Pull request merged**
