### PR TITLE
tensor2image: major change

### PR DESCRIPTION
**Pull request by ducha-aiki**
Now tensor2image converts:
[B C H W] into [B H W C]
[1 C H W] into [H W C]
[1 1 H W] into [H W]

Image2Tensor now always outputs 4d tensor [B C H W]

### CODE REVIEW

**Comment by ducha-aiki** [comment]
@edgarriba please, look at "failing" test. I think, we need to re-think, what is the expected behavior of tensor_to_image() for (1, A, B) tensor. Now it swaps dims to  (A, B, 1). That may seems logical, but the problem is the the main (in my practice the only) usage of "tensor_to_image" stuff is to then send to matplotlib and plot. But it fails with error in previous message. 

If you agree with me, then we should change what the test expects. If no, well I disagree, but feel free to close this PR then.

**Comment by edgarriba** [comment]
@ducha-aiki I'm thinking in another use cases, but cannot find new ones. Probably what you suggest is correct. If anyone complains, we can find a way to support. Actually, now that you are refactoring this, would be nice to have the following behavior too (1, 3, H, W) -> (H, W, 3) which I believe now it  doesn't happen.

**Comment by ducha-aiki** [comment]
@edgarriba I have done one more logical step to ensure cycle consistency:
Image2Tensor now always outputs 4d tensor [B C H W]
Please, review

**Comment by ducha-aiki** [comment]
I do and will :)

**Pull request merged**
